# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('_stochvolTMB_rcppeigen_hello_world', PACKAGE = 'stochvolTMB')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_stochvolTMB_rcppeigen_outerproduct', PACKAGE = 'stochvolTMB', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_stochvolTMB_rcppeigen_innerproduct', PACKAGE = 'stochvolTMB', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_stochvolTMB_rcppeigen_bothproducts', PACKAGE = 'stochvolTMB', x)
}

